package com.hibernatepractice.paymentsystem.service;



import com.hibernatepractice.paymentsystem.model.BatchReport;
import jakarta.persistence.EntityManager;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.assertNotNull;

@SpringBootTest
@Transactional
class IdGenerationTest {

    @Autowired
    private EntityManager entityManager;

    @Test
    void testIdentityGeneration() {
        BatchReport report = new BatchReport();
        report.setReportType("OVERDUE_SUMMARY");
        report.setGeneratedAt(LocalDateTime.now());

        // Save the entity
        entityManager.persist(report);
        entityManager.flush();

        // Verify the ID was generated by the strategy
        assertNotNull(report.getId());
        System.out.println("Generated ID via IDENTITY: " + report.getId());
    }
}